### ISSUE TITLE
Typo and Incorrect Count of Undergrads-midfieldterms

### ISSUE THREAD

**Issue by neilhatfield** [MIDFIELDR/midfieldr#1]
The `midfieldterms` data frame has a typo in the description file (i.e., "97,064") when I believe you meant "97640". However, I'm only finding 95,995 unique student ids in the data frame. Is there an issue with the data frame?

**Comment by graphdr** [comment]
I will take a look.

**Comment by graphdr** [comment]
Presently, I find 97640 unique IDs in midfieldstudents but, as you point out out, only 95,995 unique IDs in midfieldterms. Not sure why because I expected the number of unique IDs to be the same. I will pass this along to our data steward to find out. Thanks!

**Comment by graphdr** [comment]
Neil, 

Sorry about the tardy response, but I do have an answer for you and I've updated the help pages accordingly. 

- The "student" data table includes only students admitted as degree-seeking.
- The "term" table can include non-degree-seeking students, but the student must complete a term. Thus a student can appear in the "student" table because they are degree-seeking but not appear in "term" because they did not complete a term. Contrary-wise, a student can appear in "term" because they completed a term (perhaps as an audit) but they were never admitted as degree-seeking, so they do not appear in "student."
- The "course" table is similar to "term". 
- The "degree" table (as of the latest version of midfielddata) includes only student earning a degree. Thus, students in "degree" will appear in all three of the other data tables. 

Thank you for your question and attention to detail. 

The package has been completely overhauled since last summer: 

- the practice data sets in midfielddata have been edited (including data set name changes and edited values) to be more consistent with the research data available to MIDFIELD partners. 
- the functionality has been overhauled with a more consistent set of arguments across all functions plus runtime argument checks and unit tests recently completed
best regards, 

Richard
